name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: Check code formatting and typing
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
#            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements-dev.txt

      - name: Check format
        run: ./scripts/lint.sh check_format

      - name: Check types
        run: ./scripts/lint.sh check_types

  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
#            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements-dev.txt
          sudo apt-get install binutils-riscv64-unknown-elf gcc-riscv64-unknown-elf

      - name: Build riscv-tests
        run: |
          cd tests && make

      - name: Run tests
        run: python -m unittest riscv_simple_amaranth/test.py

